name: JS Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: |
          cd source
          yarn
      - name: Run tests
        run: |
          cd source
          yarn jest --json --outputFile="jest.results.json"
      - name: Coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "cd source && yarn jest"
        # uses: ziishaned/jest-reporter-action@872c1051350ecaf625ba2490d68e7cb63854b44c
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   test-command: "cd source && npx jest --coverage"
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: Run Jest
#       uses: stefanoeb/jest-action@1.0.3
#       with:
#         jestArgs: --coverage
#     - name: Coverage
#       uses: ziishaned/jest-reporter-action@872c1051350ecaf625ba2490d68e7cb63854b44c
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         test-command: "npx jest --coverage"

