name: JS Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: --coverage
    - name: Coverage
      uses: ziishaned/jest-reporter-action@d4e536e
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "npx jest --coverage"

