name: 'coverage'
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test-command: "npm test"
