name: 'coverage'
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jest Coverage
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
