name: 'coverage'
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jest Coverage
        id: jcov
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: "npm test"
