name: JS Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Jest and Code Coverage
        run: |
          cd source
          npx jest --coverage
